# Generated by Django 4.0.5 on 2022-07-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('in_ex', models.CharField(choices=[('income', '수입'), ('expense', '지출')], default='income', max_length=20)),
                ('method', models.CharField(choices=[('casg', '현금'), ('card', '카드'), ('transfer', '이체')], default='casg', max_length=20)),
                ('memo', models.CharField(max_length=300, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
