# Generated by Django 4.0.5 on 2022-07-07 04:26

from django.db import migrations, models

from user.gen_master_data import gen_master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='닉네임')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RunPython(gen_master),
    ]
